name: Build and deploy Node.js app to Azure Web App - app-frontend
on:
  push:
    branches:
      - backup_1
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: npm install, build
        run: |
          npm cache clean --force
          npm install
          chmod +x ./node_modules/.bin/ng
          ./node_modules/.bin/ng build --configuration=production
        working-directory: healthcare-front-office/healthcare-portal
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: '${{ github.workspace }}/healthcare-front-office/healthcare-portal/dist/healthcare-portal'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DD734FC6395B42E08723651C8FACA0FA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CE3BC2D93B4E4846A878623E8788CFDF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98B4D5CEE90141BEA3102B6A4E45EC14 }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-frontend'
          slot-name: 'Production'
          package: .
          startup-command: 'pm2 serve /home/site/wwwroot/browser --no-daemon --spa'
